run_name:
  value: test-run-please-ignore
representation:
  value: html
model:
  value: bert
context_size:
  value: 256
parent_depth:
  value: 3
vertical:
  value: movie
remove_null:
  value: false
monitor_metric:
  value: "document/instance/f1"
learning_rate:
  value: 0.00005
optimizer:
  value: adamw
batch_size:
  value: 64
num_steps:
  value: 50000
warmup_steps:
  value: 1000
validation_interval:
  value: 1000
validation_documents:
  value: 150
evaluation_method:
  value: greedy
early_stopping_patience:
  value: 20
num_workers:
  value: 8
