run_name:
  value: test-run-please-ignore
representation:
  value: html
model:
  value: bert
context_size:
  value: 256
vertical:
  value: nbaplayer
website:
  value: espn
remove_null:
  value: false
monitor_metric:
  value: "document/f1"
learning_rate:
  value: 0.00005
optimizer:
  value: adamw
batch_size:
  value: 64
num_steps:
  value: 1000
validation_interval:
  value: 100
validation_documents:
  value: 10
validation_batches:
  value: 50
early_stopping_patience:
  value: 10
num_workers:
  value: 48
