run_name:
  value: "{model}-{vertical}-{context_size}"
representation:
  value: text
model:
  value: bert
context_size:
  value: 256
vertical:
  value: book
remove_null:
  value: false
monitor_metric:
  value: em
learning_rate:
  value: 0.00005
optimizer:
  value: adamw
batch_size:
  value: 64
num_steps:
  value: 25000
validation_interval:
  value: 1000
validation_batches:
  value: 150
early_stopping_patience:
  value: 10
num_workers:
  value: 48
